export const getAllOrders = async () => {
  try {
  } catch (error) {
    throw error
  }
}
